### ISSUE TITLE
Add a contributors guide

### ISSUE THREAD

**Issue by JannikZed** [notum-cz/strapi-plugin-location#187]
Currently, it is important to build the package manually when creating a PR. The setup-package.ts file is missing in the github repo and it is not clear on how to build and run the package. We need to improve that, so that contributing is not so hard.
Furthermore, I think there is something not fully right in the build - we have the build folder and in the build folder, the package is expecting the dist folder, with the same data than the build folder already has.. so something is here definitely not clean

**Comment by omikulcik** [comment]
Hi @JannikZed. Thank you for pointing this out. I've added the guide.  The `setup-package.ts` was used in previous versions where we needed to build the package because otherwise it would not work with older versions of Strapi. Now it seems that publishing the source code to the NPM is just enough so I also deleted the unused scripts
