### ISSUE TITLE
No correct data from api request

### ISSUE THREAD

**Issue by korayrubicoda** [notum-cz/strapi-plugin-location#38]
### Describe the bug

I am using your plugin for the strap, everything was going well,
but when I make api request, it pulls all the data
Api Url
http://localhost:1337/v1/articles?$location[coords]=49.200949303006055,16.623833585841673,5000&populate=*

### Screenshots
![image](https://github.com/notum-cz/strapi-plugin-location/assets/123622521/9b919610-0a72-4da0-b277-ebcfcb452f67)
![image](https://github.com/notum-cz/strapi-plugin-location/assets/123622521/6c77e613-284a-4d94-a1b3-1ce469fbd119)

### System

- Node.js version: v16.19.0
- NPM version:8.19.3
- Strapi version: v4.12.1
- Database: PostgreSQL 15
- Operating system: MacOS 13.5.1

**Comment by omikulcik** [comment]
Hi @korayrubicoda, is the field in which you store the coordinates also named "coords"? In case the url is constructed wrongly it will return all entries.

**Comment by korayrubicoda** [comment]
yes cordinates name "coords"
![image](https://github.com/notum-cz/strapi-plugin-location/assets/123622521/b580c9b8-e164-4277-b899-bbab8ed3e8ef)
![image](https://github.com/notum-cz/strapi-plugin-location/assets/123622521/47742c9d-d7ef-488e-ba15-5cd081f5c9df)

**Comment by omikulcik** [comment]
Oh, you should test on real coordinates from the map because they are stored as geospatial data in the DB. Also try omitting the populate=* but that should not cause any problems. If that does not work I will try replicating this.

**Comment by korayrubicoda** [comment]
I tested the coordinate and it's correct
and deleted populate=*
![image](https://github.com/notum-cz/strapi-plugin-location/assets/123622521/00812409-f814-402a-90a4-07e5785d7856)
![image](https://github.com/notum-cz/strapi-plugin-location/assets/123622521/e57a8a66-edcc-411f-aec6-ba6dbe99c5fa)

**Comment by omikulcik** [comment]
I see now. For some reason your url starts with `/v1 `instead of `/api` and our middleware determines the collection type with this code `const collectionType = url.replace("/api/", "").split("/")[0].split("?")[0];` And since there is no "/api" in your request it will fail to get the correct collectionType and lets the request through. 

If you need a hotfix it should be fixed by changing the line 24 of the middleware to `const collectionType = url.replace(strapi.config.api.rest.prefix, "").split("/")[0].split("?")[0];`

I will also include this into the source code and publish a new version but I will do it tomorrow at the earliest.

**Comment by korayrubicoda** [comment]
ahh sorry i changed the code to /v1 in the instructions when installing postgres
I fixed it, now it works
thank you :)

**Comment by omikulcik** [comment]
Glad it works :)

**Comment by omikulcik** [comment]
Closed by #39
